config/routes.rb
Twitter::Application.routes.draw do

  get "sessions/new"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'tweets#index'
  resources :users
  resources :sessions
  resources :tweets, :except => [:edit]
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :content, presence: true

  after_create :notify_mentions

  def notify_mentions
    handles = User.all.pluck(:handle)
    handles.each do |handle|
      if self.content.include?(handle)
        user = User.find_by_handle(handle)
        UserMailer.notify(user, self).deliver
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tweets
  validates :email, presence: true, uniqueness: true
  validates :handle, presence: true, uniqueness: true

  after_create :send_welcome_message #, other callbacks..

  def send_welcome_message
   UserMailer.signup_confirmation(self).deliver
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      respond_to do |format|
        format.html { redirect_to tweets_path }
        format.js
      end
    else
      render 'new'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    flash[:notice] = 'Tweet deleted!'
    redirect_to tweets_path
  end

private

  def tweet_params
    params.require(:tweet).permit(:content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

private

  def user_params
    params.require(:user).permit(:email,
                                 :password,
                                 :password_confirmation,
                                 :handle)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_errors.html.erb
  <% if object.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">TwitterClone</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if current_user %>
        <li class="active"><a href="#">Logged in as <%= current_user.handle %></a></li>
        <li class="active"><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li class="active"><%= link_to "Sign Up", signup_path %></li>
        <li class="active"><%= link_to "Log In", login_path %></li>
      <% end %>

      <li class="has-dropdown">
        <a href="#">Right Button Dropdown</a>
        <ul class="dropdown">
          <li><%= link_to "New Tweet", new_tweet_path %></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">

    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "vendor/modernizr", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container flash">
      <span class="green"><%= flash[:notice] %></span>
      <span class="red"><%= flash[:alert] %></span>
    </div>

    <%= yield %>

    <%= render 'layouts/footer' %>


    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= render 'layouts/errors', :object => @tweet %>
<%= form_for @tweet, remote: true do |f| %>
  <div class="field">

    <%= f.text_area :content %>
  </div>
  <div class="actions"><%= f.submit "Tweet" %></div>
<% end %>

app/views/tweets/_tweet.html.erb
<%= form_for tweet, remote: true do |f| %>
    <%= tweet.content %>
<% end %>

app/views/tweets/create.js.erb
$('#tweetlist').append('<%= j render(@tweet) %>');

app/views/tweets/index.html.erb
<div class="row">
  <div class="large-3 columns">
    <h3>New Tweet</h3>
    <%= render 'form' %>
  </div>
  <div class="large-9 columns">
  	<h1>Tweets</h1>
  	<ul id="tweetlist">
      <% @tweets.each do |tweet| %>
        <li><%= tweet.content %></li>
       <% end %>
    </ul>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="row">

  <div class="large-9 columns">

  </div>

  <div class="large-3 columns">
  </div>

</div>

app/views/tweets/new.js.erb
$('<%= j render("form") %>');

app/views/users/index.html.erb
<div class="row">

  <div class="large-9 columns"><h1>Welcome to Twitter</h1></div>
  <div class="large-3 columns"></div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'layouts/errors', :object => @user %>

<%= form_for (@user) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :handle %><br />
    <%= f.text_field :handle %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>